###----
# pipeline params
pipeline_dir: ~/devel/my_scripts/ATAC_git/pipeline_footprint/

# tmp_dir ($SCRATCH_DIR, local_tmpdir, or /gfs/scratch)
tmp_dir: /gfs/scratch

# the genome to use (UCSC convention)
genome: mm10

genome_dir: /gfs/mirror/genomes/plain/

annotations:
    database: /gfs/mirror/annotations/mm10_ensembl91/csvdb

    # directory with annotation information
    dir: /gfs/mirror/annotations/mm10_ensembl91/

    # chrom sizes file (chromosome, size)
    chrom_sizes: /gfs/mirror/annotations/mm10_ensembl88/assembly.dir/contigs.tsv

peaks:
    # Search sequences. By default peaks will be offset to peak centre +/- 1kb
    search_range: 1000
    # If peak summits are in column 6 of BED file specify
    # "True" here to use for peak centering
    summits: False

    # bins for calculating ATAC cut sites. Do not change from 1
    bins: 1


plot:
    # window (in b.p.) centred over peak to plot
    window: 500

    # kde smoothing of ATAC cutsite frequencies is conducted by default
    # specify unsmoothed = TRUE to also plot unsmoothed data
    show_unsmoothed: TRUE

    # bandwidth for smoothing, try a few in range 2-7
    bandwidth: 3



