## pipeline_superenhancer options

# dir for tmp files ($SCRATCH_DIR, local_tmpdir, or /gfs/scratch)
tmp_dir: /gfs/scratch

# the genome to use (UCSC convention)
genome: mm10

# path to the directory containing pipeline
pipeline_dir: /home/tkhoyratty/devel/my_scripts/ATAC_git/pipeline_superenhancer/

annotations:
    database: /gfs/mirror/annotations/mm10_ensembl91/csvdb

    # directory with annotation information
    dir: /gfs/mirror/annotations/mm10_ensembl91/

    # chrom sizes file (chromosome, size)
    chrom_sizes: /gfs/mirror/annotations/mm10_ensembl91/assembly.dir/contigs.tsv

great:
    # extend basal domain up and down (bp)
    basal_up: 5000
    basal_down: 1000

    # maximum extension (bp)
    max: 1000000

    # restrict extensions to half way to the nearest gene (False|True)
    half: False

superenhancer:
    merge_dist: 12500

    # RAD21 & CTCF peaks to subtract from candidate enhancers
    # leave blank if necessary
    insulators: /home/tkhoyratty/work/IRF5/analysis/CTCF_Cohesin/tads/data.dir/insulators.bed

